/**
 * Auto-generated by hand for the ConfidentialGroupBuy demo (deployed via
 * `forge create`, not `forge script` — so `pnpm generate` cannot pick
 * it up from broadcast/). If you redeploy via a forge script, re-run
 * `pnpm generate` and this file will be replaced.
 */
import { ConfidentialGroupBuy as ConfidentialGroupBuy_LOCAL } from "./ConfidentialGroupBuy.local";
import type { ContractDeployment } from "~~/utils/contract";

const REMOTE = {
  11155111: {
    address: "0xCB4e3F1Dea12F2e4b380188F429Cccf2e8938423",
    abi: [
      {
        type: "constructor",
        inputs: [
          {
            name: "_token",
            type: "address",
            internalType: "contract IConfidentialToken",
          },
          {
            name: "_goal",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "_deadline",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "FINALITY_BLOCKS",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "confidentialProtocolId",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "creator",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "deadline",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "finalizationRequestId",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "finalizeCallback",
        inputs: [
          {
            name: "requestId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "cleartexts",
            type: "uint256[]",
            internalType: "uint256[]",
          },
          {
            name: "decryptionProof",
            type: "bytes",
            internalType: "bytes",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "finalized",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "bool",
            internalType: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getEncryptedTotal",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getMyContribution",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getTotalHandle",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "bytes32",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "goalAmount",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint64",
            internalType: "uint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "goalMet",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "bool",
            internalType: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "pledge",
        inputs: [
          {
            name: "encAmount",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "proof",
            type: "bytes",
            internalType: "bytes",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "requestFinalization",
        inputs: [],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "revealedTotal",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint64",
            internalType: "uint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "scheduleFinalization",
        inputs: [],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "scheduledRevealBlock",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "token",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address",
            internalType: "contract IConfidentialToken",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "withdrawToCreator",
        inputs: [],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "FinalizationRequested",
        inputs: [
          {
            name: "requestId",
            type: "uint256",
            indexed: false,
            internalType: "uint256",
          },
          {
            name: "totalHandle",
            type: "bytes32",
            indexed: false,
            internalType: "bytes32",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "Finalized",
        inputs: [
          {
            name: "goalMet",
            type: "bool",
            indexed: false,
            internalType: "bool",
          },
          {
            name: "total",
            type: "uint64",
            indexed: false,
            internalType: "uint64",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "Pledged",
        inputs: [
          {
            name: "backer",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "transferredHandle",
            type: "bytes32",
            indexed: false,
            internalType: "bytes32",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "PublicDecryptionVerified",
        inputs: [
          {
            name: "handlesList",
            type: "bytes32[]",
            indexed: false,
            internalType: "bytes32[]",
          },
          {
            name: "abiEncodedCleartexts",
            type: "bytes",
            indexed: false,
            internalType: "bytes",
          },
        ],
        anonymous: false,
      },
      {
        type: "error",
        name: "InvalidKMSSignatures",
        inputs: [],
      },
      {
        type: "error",
        name: "SenderNotAllowedToUseHandle",
        inputs: [
          {
            name: "handle",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "sender",
            type: "address",
            internalType: "address",
          },
        ],
      },
      {
        type: "error",
        name: "ZamaProtocolUnsupported",
        inputs: [],
      },
    ],
    deployedOnBlock: 0,
  },
} as const;

export const ConfidentialGroupBuy = {
  ...REMOTE,
  ...ConfidentialGroupBuy_LOCAL,
} as const satisfies Partial<Record<number, ContractDeployment>>;
