/**
 * Auto-generated by hand for the ConfidentialGroupBuy demo (deployed via
 * `forge create`, not `forge script` — so `pnpm generate` cannot pick
 * it up from broadcast/). If you redeploy via a forge script, re-run
 * `pnpm generate` and this file will be replaced.
 */
import { MockCToken as MockCToken_LOCAL } from "./MockCToken.local";
import type { ContractDeployment } from "~~/utils/contract";

const REMOTE = {
  11155111: {
    address: "0x9Ab7912a600049De984E4C79AfC90E34eE17c08f",
    abi: [
      {
        type: "function",
        name: "balances",
        inputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "confidentialProtocolId",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "mint",
        inputs: [
          {
            name: "to",
            type: "address",
            internalType: "address",
          },
          {
            name: "enc",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "proof",
            type: "bytes",
            internalType: "bytes",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferFromValidated",
        inputs: [
          {
            name: "from",
            type: "address",
            internalType: "address",
          },
          {
            name: "to",
            type: "address",
            internalType: "address",
          },
          {
            name: "amount",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        outputs: [
          {
            name: "transferred",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferValidated",
        inputs: [
          {
            name: "to",
            type: "address",
            internalType: "address",
          },
          {
            name: "amount",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        outputs: [
          {
            name: "transferred",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "error",
        name: "SenderNotAllowedToUseHandle",
        inputs: [
          {
            name: "handle",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "sender",
            type: "address",
            internalType: "address",
          },
        ],
      },
      {
        type: "error",
        name: "ZamaProtocolUnsupported",
        inputs: [],
      },
    ],
    deployedOnBlock: 0,
  },
} as const;

export const MockCToken = {
  ...REMOTE,
  ...MockCToken_LOCAL,
} as const satisfies Partial<Record<number, ContractDeployment>>;
